export const CHANGE_USERNAME = 'CHANGE_USERNAME';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_ADMIN_STATUS = 'CHANGE_ADMIN_STATUS';
export const CHANGE_LOGGED_STATUS = 'CHANGE_LOGGED_STATUS';

export const EXCEL_IS_POLARION = 'EXCEL_IS_POLARION';
export const EXCEL_SHOW_NAMES = 'EXCEL_SHOW_NAMES';
export const EXCEL_ISSUE_LIST = 'EXCEL_ISSUE_LIST';
export const EXCEL_END_DATE = 'EXCEL_END_DATE';
export const EXCEL_START_DATE = 'EXCEL_START_DATE';
export const EXCEL_DATA = 'EXCEL_DATA';
export const FIRST_LOAD = 'FIRST_LOAD';




